package ep.opensource.jpa.legacy.persistence.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Specifies the mapped column for a persistent property or field. If no Column annotation is specified, the default
 */
@Target(value=FIELD)
@Retention(value=RUNTIME)
public @interface Column {
    /**
     * (Optional) The name of the column. Defaults to the property or field name.
     */
    String name() default "";
    
    /**
     * (Optional) The name of the table that contains the column. If absent the column is assumed to be in the primary
     * table.
     */
    String table() default "";
    
    /**
     * (Optional) Whether the database column is nullable.
     */
    boolean nullable() default true;
    
    /**
     * (Optional) Whether the column is included in SQL INSERT statements generated by the persistence provider.
     */
    boolean insertable() default true; 
    
    /**
     * (Optional) Whether the column is included in SQL UPDATE statements generated by the persistence provider.
     */
    boolean updatable() default true; 
}
